### ISSUE TITLE
Why can't I import the pvdn package

### ISSUE THREAD

**Issue by s1mpleee** [larsOhne/pvdn#4]
![2021-07-10 09-17-00 的屏幕截图](https://user-images.githubusercontent.com/68166466/125147801-3ce9d700-e160-11eb-9d0c-0900e905ab3a.png)

**Comment by lukazso** [comment]
You probably did not install the package. Navigate into the pvdn base directory, setup a new virtual environment, and install it via pip:

```bash
python3 -m venv venv
pip3 install -e .
```

Also, remember to compile the C++ libraries:

```
cd pvdn/detection/utils
./compile_image_operations
```

Now you should be good to go.
